export const API_IS_LOADING = 'API_IS_LOADING';
export const API_LOADING_SUCCESS = 'API_LOADING_SUCCESS';
export const API_LOADING_ERROR = 'API_LOADING_ERROR';
export const FETCH_DISCOUNT_CODE = 'FETCH_DISCOUNT_CODE';
export const DISCOUNT_CODE_SUCCESS = 'DISCOUNT_CODE_SUCCESS';
export const DISCOUNT_CODE_FAILURE = 'DISCOUNT_CODE_FAILURE';
export const DISCOUNT_ATTEMPT = 'DISCOUNT_ATTEMPT';